# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
            pdo_mysql:
                entity:
                    class: AppBundle\AppBundle:User
                    property: username


    firewalls:
        login_firewall:
            pattern: ^/login$
            anonymous: ~

        secured_area:
            pattern: ^/
            http_basic: ~
            form_login:
                check_path: login_check
                login_path: login

        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: pdo_mysql

            #form_login:
            #    login_path: login
            #    check_path: login


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
